import type { Metadata } from "next";
import { Inter, Lora, Open_Sans } from "next/font/google";

import { ContextProvider } from "@/components/context-provider";
import { cn } from "@/lib/utils";

import "../styles/globals.css";

const lora = Lora({ subsets: ["latin"], variable: "--font-serif" });
const openSans = Open_Sans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ContextProvider>
      <html lang="en">
        <body className={`${lora.className} ${openSans.className}`}>
          {children}
        </body>
      </html>
    </ContextProvider>
  );
}
