import type { Metadata } from "next";
import { Lora, Open_Sans } from "next/font/google";

import SiteFooter from "@/components/layout/site-footer";
import SiteHeader from "@/components/layout/site-header";
import { ContextProvider } from "@/providers/context-provider";
import { ThemeProvider } from "@/providers/theme-provider";

import "../styles/globals.css";

const lora = Lora({ subsets: ["latin"], variable: "--font-serif" });
const openSans = Open_Sans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ContextProvider>
      <html lang="en">
        <body
          className={`${lora.className} ${openSans.className} flex min-h-screen flex-col antialiased`}
        >
          <ThemeProvider attribute="class" defaultTheme="system">
            <SiteHeader />
            <main className="flex-1 py-6">{children}</main>
            <SiteFooter />
          </ThemeProvider>
        </body>
      </html>
    </ContextProvider>
  );
}
